### ISSUE TITLE
replace-text

### ISSUE THREAD

**Issue by andyoulovexy** [renber/pdf-revise#4]
replace-text can't work. How can i do?

**Comment by LunaticShade** [comment]
Yes, currently replace-text is experimental and won't work in many cases.
Did you try to use supersede-text?

**Comment by andyoulovexy** [comment]
> Yes, currently replace-text is experimental and won't work in many cases. Did you try to use supersede-text?

supersede-text work .Thanks

**Comment by renber** [comment]
Good to hear that it works
